# Generated by Django 3.0.3 on 2020-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200221_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='response',
            name='context',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Welcome'), (1, 'Take Size'), (2, 'Take Toppings'), (3, 'Take Quantity'), (4, 'Take Name'), (5, 'Take Address'), (6, 'Take Confirmation'), (7, 'Get Pizza Status'), (10, 'Fallback')]),
        ),
    ]
