# Generated by Django 3.0.3 on 2020-02-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pizza', to='chatbot.Pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='context',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Welcome'), (1, 'Take Pizza'), (2, 'Take Size'), (3, 'Take Quantity'), (4, 'Take Name'), (5, 'Take Address'), (6, 'Take Confirmation'), (7, 'Get Pizza Status'), (10, 'Fallback')]),
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
